export const ARTICLE_FETCH_SUCCESS = 'ARTICLE_FETCH_SUCCESS';
export const ARTICLE_FETCH = 'ARTICLE_FETCH';
export const ARTICLE_FETCH_FAILURE = 'ARTICLE_FETCH_FAILURE';

export const ARTICLE_SAVE = 'ARTICLE_SAVE';
export const ARTICLE_SAVE_SUCCESS = 'ARTICLE_SAVE_SUCCESS';
export const ARTICLE_SAVE_FAILURE = 'ARTICLE_SAVE_FAILURE';

export const ARTICLE_PUBLISH = 'ARTICLE_PUBLISH';
