language: node_js
node_js:
  - "stable"
env:
  global:
    - CC_TEST_REPORTER_ID=2f0bee182854b9bba4aa286a463fa3015d47f3cf22ef54e915af0406a417f5f3
cache:
  directories:
    - "node_modules"
install:
  - npm install
before_script:
  - npm install codeclimate-test-reporter -g
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test -- --coverage
  - npm build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
