export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const FETCH_MORE_ARTICLES_SUCCESS = "FETCH_MORE_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_FAILURE = "FETCH_ARTICLES_FAILURE";
