export const COMMENTING = "COMMENTING";
export const COMMENTING_SUCCESS = "COMMENTING_SUCCESS";
export const COMMENTING_FAILED = "COMMENTING_FAILED";
export const FETCHING_COMMENT_AUTHORS = "FETCHING_COMMENT_AUTHORS";
export const FETCHING_COMMENT_AUTHORS_SUCCESS = "FETCHING_COMMENT_AUTHORS_SUCCESS";
export const UPDATING_COMMENT = "UPDATING_COMMENT";
export const UPDATING_COMMENT_SUCCESS = "UPDATING_COMMENT_SUCCESS";
export const UPDATING_COMMENT_FAILED = "UPDATING_COMMENT_FAILED";
