export const successData = {
  stats: [
    {
      slug: "hello-world-24b8q0pypck4",
      title: "Hello World",
      view_count: 17,
      comment_count: 22,
      like_count: 28,
      dislike_count: 28,
      average_rating: 34,
    },
    {
      slug: "hjbjbjkj-99lbcr9akkjc",
      title: "hjbjbjkj",
      view_count: 5,
      comment_count: 96,
      like_count: 33,
      dislike_count: 45,
      average_rating: 5,
    },
    {
      slug: "how-to-train-your-dragon-today-ehit7dguf71r",
      title: "How to train your dragon today",
      view_count: 102,
      comment_count: 12,
      like_count: 23,
      dislike_count: 87,
      average_rating: 2,
    },
    {
      slug: "how-to-train-your-dragon-today-090i344spmau",
      title: "How to train your dragon today",
      view_count: 254,
      comment_count: 99,
      like_count: 2,
      dislike_count: 6,
      average_rating: 5,
    },
  ],
};
