export const FETCH_STATS_REQUEST = "FETCH_STATS_REQUEST";
export const FETCH_STATS_SUCCESS = "FETCH_STATS_SUCCESS";
export const FETCH_STATS_FAIL = "FETCH_STATS_FAIL";
export const REFRESH_STATS_REQUEST = "REFRESH_STATS_REQUEST";
export const REFRESH_STATS_SUCCESS = "REFRESH_STATS_SUCCESS";
export const REFRESH_STATS_FAIL = "REFRESH_STATS_FAIL";
