export default {
  VERTICAL_LAYOUT: "VERTICAL_LAYOUT",
  HORIZONTAL_REVERSE_LAYOUT: "HORIZONTAL_REVERSE_LAYOUT",
  HORIZONTAL_LAYOUT: "HORIZONTAL_LAYOUT",
  MINIMAL_LAYOUT: "MINIMAL_LAYOUT",
  MINIMAL_AUTHOR_LAYOUT: "MINIMAL_AUTHOR_LAYOUT",
};
