export const RESET_GENERIC_ERROR = 'RESET_GENERIC_ERROR';
export const RESET_FIELD_ERROR = 'RESET_FIELD_ERROR';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
