export const LIKE_ARTICLE = 'LIKE_ARTICLE';
export const DISLIKE_ARTICLE = 'DISLIKE_ARTICLE';
export const LIKE_DISLIKE_ERROR = 'LIKE_DISLIKE_ERROR';
export const UNLIKE_ARTICLE = 'UNLIKE_ARTICLE';
export const UNDISLIKE_ARTICLE = 'UNDISLIKE_ARTICLE';
