export const SUBSCRIBE_NOTIFICATIONS_SUCCESS = 'SUBSCRIBE_NOTIFICATIONS_SUCCESS';
export const UNSUBSCRIBE_NOTIFICATIONS_SUCCESS = 'UNSUBSCRIBE_NOTIFICATIONS_SUCCESS';
export const SUBSCRIBE_UNSUBSCRIBE_FAILURE = 'SUBSCRIBE_UNSUBSCRIBE_FAILURE';
export const FETCH_SUBSCRIPTION_STATUS = 'FETCH_SUBSCRIPTION_STATUS';
export const FETCH_SUBSCRIPTION_STATUS_FAILURE = 'FETCH_SUBSCRIPTION_STATUS_FAILURE';
