export const SUBSCRIBE_NOTIFICATIONS_SUCCESS = 'SUBSCRIBE_NOTIFICATIONS_SUCCESS';
export const UNSUBSCRIBE_NOTIFICATIONS_SUCCESS = 'UNSUBSCRIBE_NOTIFICATIONS_SUCCESS';
export const SUBSCRIBE_UNSUBSCRIBE_FAILURE = 'SUBSCRIBE_UNSUBSCRIBE_FAILURE';
